name: Saad-VLESS-Turbo
on: 
  workflow_dispatch:
jobs:
  run-vless:
    runs-on: ubuntu-latest
    steps:
      - name: Run Server
        run: |
          # تحميل xray
          bash <(curl -L https://github.com/XTLS/Xray-install/raw/main/install-release.sh)
          
          # إعداد السيرفر (VLESS + WS)
          cat <<EOF > /usr/local/etc/xray/config.json
          {
            "inbounds": [{
              "port": 8080,
              "protocol": "vless",
              "settings": {
                "clients": [{"id": "saad-1122-3344-5566-778899aabbcc"}],
                "decryption": "none"
              },
              "streamSettings": {
                "network": "ws",
                "wsSettings": {"path": "/saad-turbo"}
              }
            }],
            "outbounds": [{"protocol": "freedom"}]
          }
          EOF
          
          # تشغيل النفق
          curl -L https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -o cf && chmod +x cf
          xray run -c /usr/local/etc/xray/config.json &
          ./cf tunnel --url http://localhost:8080
